In [9]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import seaborn as sns

In [10]:
accesos_tec_localidades= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_Accesos_Tecnologia_Localidades.parquet")

accesos_tec_localidades.head()

   linkindec     provincia     partido   localidad    tecnologia  accesos
0    6854100  BUENOS AIRES  25 de Mayo  25 de Mayo          ADSL      755
1    6854100  BUENOS AIRES  25 de Mayo  25 de Mayo    CABLEMODEM     4600
2    6854100  BUENOS AIRES  25 de Mayo  25 de Mayo  FIBRA OPTICA        2
3    6854100  BUENOS AIRES  25 de Mayo  25 de Mayo     SATELITAL      776
4    6854100  BUENOS AIRES  25 de Mayo  25 de Mayo      WIRELESS      727

In [12]:
accesos_tec_provincias= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_Accesos_Tecnologia_Provincias.parquet")

accesos_tec_provincias.head()

,año,trimestre,provincia,adsl,cablemodem,fibra_optica,wireless,otros,total
0,2024,3,Buenos Aires,222003,2689425,1895514,144449,73496,5024887
1,2024,3,Capital Federal,52604,1116716,254994,4493,30648,1459455
2,2024,3,Catamarca,4646,10053,59975,1384,890,76948
3,2024,3,Chaco,8366,57194,85610,8548,2649,162367
4,2024,3,Chubut,25955,80405,26555,31118,11776,175809

In [13]:
accesos_tec_totales= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_Accesos_Tecnologia_Totales.parquet")

accesos_tec_totales.head()

,año,trimestre,adsl,cablemodem,fibra_optica,wireless,otros,total
0,2024,3,721676,5787585,4315339,608325,264037,11696962
1,2024,2,733491,5867504,4169958,593197,191957,11556107
2,2024,1,774475,5986957,4015101,598682,257941,11633156
3,2023,4,836390,6022532,3908183,585760,194796,11547661
4,2023,3,897895,6018832,3708718,581436,200027,11406908

In [15]:
accesos_rango_provincias= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_Accesos_Velocidad_Rango_Provincias.parquet")

accesos_rango_provincias.head()

,año,trimestre,provincia,hasta_512_kbps,+_512_kbps_-_1_mbps,+_1_mbps_-_6_mbps,+_6_mbps_-_10_mbps,+_10_mbps_-_20_mbps,+_20_mbps_-_30_mbps,+_30_mbps,otros,total
0,2024,3,Buenos Aires,26909,23962,228393,239339,246144,110876,4042646,93351,5011620
1,2024,3,Capital Federal,516,4544,26409,48083,33925,5829,1355061,0,1474367
2,2024,3,Catamarca,71,209,3065,3734,4423,1827,61181,77,74587
3,2024,3,Chaco,236,477,14811,10361,6247,5729,105485,4040,147386
4,2024,3,Chubut,111,1088,44276,31402,22843,20196,33665,16589,170170

In [17]:
internet_BAF_provincias= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_BAF_Provincias.parquet")

internet_BAF_provincias.head()

    año  trimestre        provincia  banda_ancha_fija  dial_up    total
0  2024          3     Buenos Aires           5018987     5900  5024887
1  2024          3  Capital Federal           1457405     2050  1459455
2  2024          3        Catamarca             76947        1    76948
3  2024          3            Chaco            162362        5   162367
4  2024          3           Chubut            174952      857   175809

In [19]:
internet_ingresos= pd.read_parquet("C:/Users/jugas/OneDrive/Escritorio/Proyecto ENACOM/dashboard-conectividad-ENACOM/data/Internet_ingresos.parquet")

internet_ingresos.head()

    año  trimestre      ingresos
0  2024          3  541734583,50
1  2024          2  442032166,69
2  2024          1  346198986,13
3  2023          4  167376014,80
4  2023          3  133106593,41